# Einführung und Überblick {#intro}

## Wozu Mixed Methods? 

In einer ersten, einfachen Definition werden mit Mixed Methods empirische Forschungsprojekte bezeichnet, in denen qualitative und quantitative Methoden kombiniert werden. Diese erste Annäherung ist hilfreich, weil sie eine zentrale Herausforderung betont: Verschiedene Methoden in einem Projekt oder Forschungskontext zusammenzuführen, die historisch häufig in aktiver Abgrenzung zueinander entwickelt wurden. 

Entscheidend ist allerdings nicht so sehr der Umstand, dass qualitative und quantitative Methoden verbunden werden, sondern wie genau diese Verbindungen hergestellt, begründet und reflektiert werden. *Wie* man also Methoden aufeinander wie auch auf den Forschungsgegenstand und die Zielsetzungen eines Projekts abstimmt, ist die entscheidende Frage. 

Im Zuge dieser *begründeten und reflektierten Kombination von Methoden* kommen zwangsläufig Fragen auf, die nicht nur für Mixed Methods wichtig sind, sondern von allgemeinem methodologischen Interesse sind: 

- Das entscheidende Anliegen von Mixed Methods wird meist darin gesehen, dem **Forschungsvorhaben** angemessene Forschungsprozesse zu gestalten. Doch was bedeutet das genau und wie stellt man "Angemessenheit" von Methoden her?

- Im Vergleich zum nach wie vor starken "Werkzeugkasten-Denken" in anderen Bereichen der Methodenlehre und -entwicklung rückt im Feld von Mixed Methods der Fokus auf **Designfragen** -- und damit auch auf **grundlegende Logiken** und **wissenschaftstheoretische Grundlagen** empirischer Forschung.

- Die Orientierung auf Angemessenheit und Designfragen spiegelt sich in der expliziten Anerkennung der **Rolle von Forschungsfragen** wider. In kaum einem anderen Bereich der sozialwissenschaftlichen Methodenlandschaft wird diesem Aspekt vergleichbar viel Aufmerksamkeit geschenkt. 

Diese und andere Eigenheiten verweisen auf sozialwissenschaftliche Grundkompetenzen, für die in der traditionellen Methodenlehre in der Regel relativ wenig Zeit bleibt. Der Zweck der Beschäftigung mit Mixed Methods liegt daher nicht zuletzt darin, diese oft vernachlässigten **Kompetenzen zu trainieren**, selbst wenn aktuell an keinem eigenen qualitativ-plus-quantitativen Forschungsprojekt gebastelt wird. Denn erstens tragen diese Fertigkeiten auch in "rein qualitativen" und "rein quantitativen" Projekten zur bewussten Gestaltung von kohärenten und produktiven Forschungsprozessen bei. Zweitens geht es in den Sozialwissenschaften auch darum, mit den Forschungsarbeiten anderer umgehen zu können. Mixed Methods stehen in diesem Sinn auch für die Aneignung einer **Rezeptionsfertigkeit**: verstehen, was andere Forschende tun, und sich aktiv und kompetent auf ihre Ergebnisse beziehen können. 

Dieser Logik folgend gliedert sich dieses Online-Buch grob in zwei Teile. Die ersten Abschnitte widmen sich grundlegenden Aspekten empirischer Forschung, die für ein Verständnis von Mixed Methods essenziell sind: die Unterscheidung von qualitativen und quantitativen Methoden, das Verhältnis von Design- und Methodenfragen, die Rolle von Forschungsfragen und die Bestimmung von Gegenständen und Zielen eines Forschungsprojekts. Die anschließenden Abschnitte wenden sich dann der Mixed-Methods-Forschung in ihrer aktuell vorherrschenden Form zu. 

## Inhalte im Überblick 

Die Kapitel dieses Skriptums tasten sich von eher abstrakten Grundlagenfragen schrittweise zu konkreten Forschungsszenarien vor. Die folgenden Themen werden behandelt: 

1. [**Designs und Methoden -- zwei Blickwinkel auf empirische Forschung**](#designsmethoden): Für die Beschäftigung mit Mixed Methods ist die Differenzierung von Design- und Methodenfragen zentral. Mixed-Methods-Projekte sind häufig nicht nur multimethodisch, sondern kombinieren auch Facetten der drei sozialwissenschaftlichen Grunddesigns (Experiment, Erhebung, Fallstudie). Wer Methoden angemessen und bewusst verbinden will, muss auf beiden diesen Ebenen über Forschung nachdenken und kommunizieren.

2.  [**Mixed Methods und die Unterscheidung von qualitativen und quantitativen Methoden**](#qualquan): Die Unterscheidung von qualitativer und quantitativer Forschung ist für Mixed Methods von zentraler Bedeutung. Diese Unterscheidung ist einerseits irreführend, anderereits aber auch erhellend und in vielen Hinsichten angemessen. Ob sie sinnvoll ist oder nicht, ist letzten Endes eine Frage des Blickwinkels bzw. der Tiefenschärfe. 

3. [**Gegenstände und Ziele als zentrale Bezugspunkte**](#gegenstaendeziele): Eine Antwort darauf, wie Forschungsfragen die Methodenwahl bestimmen können, lautet: Weil Forschungsfragen den Gegenstand und die (Generalisierungs-)Ziele eines Projekts definieren. Es ist daher entscheidend, diese beiden Aspekte eines Forschungsvorhabens klar zu fassen. Zur Zieldefinition gehört auch, den Grund für die Kombination qualitativer und quantitativer Methoden beim Namen zu nennen (kombiniern, um zu validieren, zu illustrieren, zu vertiefen, zu ergänzen ...). 

4. [**Forschungsfragen und ihre Funktionen für die empirische Forschung**](#forschungsfragen): Das zentrale Mantra der Mixed-Methods-Forschung besagt, dass die Forschungsfrage die Methodenwahl bestimmen soll (und nicht umgekehrt Methodenvorlieben Fragen vorgeben sollen). Aber wie genau ergeben sich *Methoden* aus einer *Frage*? Was macht eine (gute) Forschungsfrage eigentlich genau aus? Wieso sind Forschungsfragen so wichtig? Und wie findet man sie?

5. [**Mixed Methods systematisieren I -- Typologien**](#typologien): Die Flexibilität, Adaptivität und Komplexität von Mixed Methods impliziert eine ungeheure Fülle an Möglichkeiten, wie ein konkretes Projekt aussehen kann. Typologien haben sich als eine von drei zentralen Wegen erwiesen, Ordnung in diese Vielfalt zu bringen. Entscheidend sind dabei die Kriterien, nach denen typologisiert wird. Die Identifikation eines passenden Typs von Mixed-Methods-Design kann helfen, einen realistischen Weg zur Umsetzung eines Projekts zu finden. 

6. [**Mixed Methods systematisieren II -- Notationen**](#notationen): Notationen sind neben Typologien eine zweite Möglichkeit, Mixed Methods systematisch darzustellen. Im Vergleich zu Typologien legen Notationen stärkeres Gewicht auf die grundlegende Logik eines Projekts. Sie sind zudem leicht zu verstehen und damit auch leicht zu kommunizieren. 

8. [**Mixed Methods ohne Mixing**](#ohnemixing): Für kleinere Forschungsprojekte -- etwa für eine Bachelor- oder Masterarbeit -- ist es kaum realistisch machbar, mehrere Forschungsmethoden konsequent einzusetzen. Das bedeutet aber nicht, dass man sich nicht von Mixed Methods inspirieren lassen kann. Es gibt verschiedene Wege, "sekundäre" Mixed-Methods-Projekte umzusetzen. 
