# (PART) Techniken und Wege der konkreten Umsetzung {-}

# Mixed Methods systematisieren I: Typologien {#typologien}

Es ist eine fast schon identitätsstiftende Eigenheit von Mixed Methods, Forschungsdesigns in **Typologien** einzuteilen [@creswell2003]. Der Begriff des Designs wird dabei deutlich konkreter gefasst als in der Unterscheidung der [drei Grunddesigns sozialwissenschaftlicher Forschung](#designsmethoden). Die Grundidee bleibt aber dieselbe: Es geht darum, methodologisch *schlüssige*, empirisch *produktive* und praktisch *machbare* Wege aufzuzeigen, Erkenntnisziele zu einem bestimmten Forschungsgegenstand zu erreichen. 

Die Gründe für die Neigung zur "Typenbildung" in der Mixed-Methods-Literatur sind vielfältig [@@teddlie2006]. In ihr kommt natürlich zum einen die Komplexität und den Variantenreichtum von Mixed-Methods-Projekten zum Ausdruck, die (im Gegensatz zu einer Fragebogenerhebung oder einem Experiment) nicht nach einem fixen und immer gleichen Schema ablaufen können. Sie spiegelt aber auch eine Art von philosophischer Haltung wider, nach der nicht abstrakte normative Vorstellungen idealer Wissenschaft, sondern reale Forschungabläufe Ausgangspunkt methodologischer Reflexion sein sollten macht. Nicht zuletzt geht es auch um die Ausarbeitung einer gemeinsamen Sprache und geteilter Standards, darum, Richtlinien zu definieren, um Mixed-Methods-Projekte nachvollziehbar gestalten und bewerten zu können. 

## MM-Typologien: ein Beispiel

Wer sich in die Mixed-Methods-Literatur vertieft, kann den Eindruck gewinnen, dass es so viele verschiedene MM-Typologien wie  MM-Autor*innen gibt. Manche Typologien unterscheiden relativ grobschlächtig eine Handvoll von typischen Forschungsszenarien, andere sind deutlich feingliedriger und identifizieren Dutzende Typen von MM-Designs.

Um die Grundidee zu verstehen, ist es sinnvoll, sich mit einer exemplarischen Typologie vertraut zu machen. Dazu bietet sich jene von Creswell & Plano Clark [@creswell2018] an, die sich mittlerweile als eine Art Standard etabliert hat. Unterschieden werden sechs zentrale Arten von MM-Projekten:

**1. Convergent Parallel Design**: Qualitative und quantitative Methoden werden in diesem Design gleichzeitig (das heißt: in keiner logisch notwendigen Reihenfolge) eingesetzt, um den Forschungsgegenstand aus unterschiedlichen Perspektiven in den Blick nehmen zu können (der Begriff der *Triangulation* kann daher auch als Synonym für diesen Typ der Methodenintegration gelten). Qualitative und quantitative Befunde werden in der Regel am Ende des Forschungsprozesses aufeinander bezogen und kontrastiert. Datenerhebung und Datenanalyse laufen also getrennt ab, die Integration von qualitativen und quantitativen Befunden findet ex-post statt. 

**2. Explanatory Sequential Design**: In einem explanatorischen Design hat die quantitative Komponente Vorrang. Der Vorrang ist ein zeitlicher, nicht unbedingt einer der Gewichtung. Qualitative Methoden werden einer zweiten Forschungsphase genutzt, um Muster aus der ersten quantitativen Phase vertiefend zu untersuchen (in der Regel um sie zu *erklären*, daher der Name des Designs). Quantitative Daten müssen also erhoben und analysiert sein, bevor der qualitative Part starten kann. 

**3. Exploratory Sequential Design**: Vorrang hat in diesem Fall (wieder: von der Reihenfolge, nicht zwangsläufig vom Stellenwert her) die qualitative Komponente. Die Daten aus dieser müssen erhoben und analysiert sein, bevor quantitative Methoden genutzt werden, um beispielsweise die Häufigkeit von qualitativ eruierten Konstellationen festzustellen oder auch um Hypothesen zu testen, die sich aus der qualitativen Forschung ergeben. (Dieser Designtyp entspricht einem Szenario, das in der deutschsprachigen Methodenliteratur lange Zeit als einziges "Mixed-Methods-Design" ernsthaft Erwähnung gefunden hat: Auf eine explorative qualitative folgt eine hypothesenprüfende quantitative Studie.)

**4. Embedded Design**: In diesem Fall hat entweder der qualitative oder der quantitative Part klar Priorität, das jeweils andere Methodeninstrumentarium kommt nur "eingebettet" ins Spiel, quasi als Hilfsmittel zu klar umrissenen Zwecken. Ein Grenzfall eines solchen Designtyps wäre die Inklusion von sehr offenen Items in eine Fragebogenerhebung oder eine kleine numerische Auszählung in einer ansonsten durch und durch qualitativen Studie. Eine etwas ambitioniertere Variante wäre z.B. eine Fragebogenerhebung, die im Rahmen einer ethnographischen Studie stattfindet; oder eine qualitative Interviewstudie, die ein Laborexperiment begleitet. 

**5. Transformative Design**: Dieser "Designtyp" durchbricht das bisherige Schema deutlich. Kennzeichnend für diesen Typ von MM-Projekt ist, dass es sozialkritsch/politisch motiviert ist und emanzipatorisch verändernd auf die soziale Welt einwirken will. Diese Zielsetzung ist klar normativ, muss aber sozialtheoretisch verankert sein und methodologisch reflektiert in Forschungsaktivitäten überführt werden. 

**6. Multiphase Design**: Dieser letzte Designtyp soll all jene Projekte umfassen, die Aspekte verschiedener Designs aufgreifen und kombinieren. Multiphase-Projekte sind ihrer Anlage nach komplex und vielschichtig und bestehen entweder aus mehr als nur zwei "Sequenzen"/Forschungsphasen oder kombinieren sequenzielle mit parallel ablaufenden Komponenten. In der Praxis folgen sehr viele Designs diesem Typ. Es handelt sich um eine Art "Sonstige"-Kategorie, die für alle etwas anspruchsvolleren Projekte reserviert ist. 

Das Schema von Creswell & Plano Clark kann als "typische Typologie" gelten -- sie ähnelt anderen Mixed-Methods-Typologien und greift Anregungen aus diesen auf (wie viel die beiden von anderen gelernt haben, zeigt sich, wenn man frühe Versionen bzw. direkte Vorläufer ihrer Typologie mit der aktuellen Fassung vergleicht, siehe etwa Creswell et al. 2003). 

Um die Finessen dieser und anderer Typologien zu verstehen, lohnt es sich, andere Vorschläge vergleichend anzusehen. So schlagen andere Autoren Typologien vor, die auch rein qualitative und rein quantitative Projekte umfassen. Ein Beispiel ist die "Methods-Strand-Matrix" [@teddlie2006], die unter anderem für ihre **Conversion Designs** Beachtung verdient. Diese zeichnen sich dadurch aus, dass die Daten aus einer Komponente in die methodische Logik der anderen übersetzt werden; Teddlie und Tashakorrie sprechen vom *Quantitizing* qualitativer Daten, wenn etwa Kategorien aus einer qualitativen Inhaltsanalyse in statistische Modellierungen einfliessen, und vom *Qualitizing* quantitativer Daten, wenn umgekehrt statistische Ergebnisse zum Inhalt einer interpretativen Analyse werden. 

## Was wirklich zählt: Kriterien der Typenbildung 

Design-Typologisierung kommen mit ihren eigenen Fallstricken: Soll eine solche wirklich systematisch sein, wird sie sehr groß und unübersichtlich; wird sie demgegnüber übersichtlich und handhabbar gehalten, kann sie schnell willkürlich wirken. So steht Typ 4 ("Transformative Design") seltsam quer zu den anderen; kann ein MM-Projekt nicht sowohl "transformativ" als auch, beispielsweise, "explanativ" sein? Und wieso taucht die Frage der Normativität, die für transformative Designs absolut prägend ist, in den anderen Typen gar nicht auf? 

Der Wert von Mixed-Methods-Typologien liegt daher bei näherer Betrachtung nicht so sehr in den identifizierten Typen selbst. Entscheidend sind vielmehr die Kriterien, nach denen diese gebildet werden. Die Typen selbst können hilfreich sein, um ein Projekt schnell und für ein Fachpublikum verständlich zu charaktisieren. Für die Gestaltung und Bewertung eines Projekts muss aber tiefer geschürft werden. Die Kriterien einer Typologisierung können dabei als Richtschnüre dienen. 

Achtet man mehr auf die Kriterien denn auf die Typen, zeigen sich zwischen den vielen Mixed-Methods-Typologien erstaunliche Ähnlichkeiten. Zu den zentralen Kriterien, die immer wieder auftauchen, zählen: 

- **Grund für Methodenkombination**: In einigen Typologien ist es das zentrale Kriterium, in anderen ist es implizit bedeutsam: Aus welchem Grund sollen überhaupt qualitative und quantitative Methoden kombiniert werden? Im Schema von Creswell & Plano Clark ist dieser Aspekt unter der Oberfläche präsent, wenn beispielsweise in einem "Sequential Explanatory Design", qualitative Methoden genutzt werden, *um zu* erklären was auf Basis von nur quantitativen Daten nur als deskriptive Korrelationen beobachtet werden kann. Bei anderen Autor*innen ist dieses Kriterium das übergeordnete und entsprechend tonangebend [beispielsweise @greene1989; @bryman2016a]. 

- **Priorität**: Eines der zentralen Kriterien für viele Typologien ist der relative Stellenwert von qualitativen und quantitativen Methoden. Für jedes Projekt sollte also überlegt werden: Sprechen die [gegebenen Erkenntnisziele und der gegebene Gegenstand](#gegenstaendeziele) für ein eher qualitatives oder ein eher quantitatives Projekt? Oder ergibt sich eher ein ausgewogenes Verhältnis? 

- **Integrationspunkte und Schnittstellen**: Dass qualitative und quantitative Methoden kombiniert werden, sagt noch nichts darüber aus, wie und an welcher Stelle im Forschungsprozess das passiert. Hier gilt es präzise zu sein: Soll der Gegenstand (wie in der klassischen Triangulation) aus verschiedenen -- das heißt eigenständigen und weitgehend getrennten -- Blickwinkeln ausgelotet werden? Dann findet die Integration in der Phase der abschließenden Interpretation oder Ergebnisdiskussion statt. Oder sollen die Ergebnisse eines Elemente für die Gestaltung eines anderen verwendet werden? Falls ja, wie und wo genau (soll die Information aus Phase 1 für die Gestaltung eines *Erhebungsinstruments* oder eher für die *Stichprobengestaltung* in Phase 2 genutzt werden)? Oder geht es darum, parallel an qualitativen und quantitativen Daten zu arbeiten, diese aber ständig aufeinander zu beziehen (etwa, wenn qualitative Interviews und Daten aus einer Fragebogenerhebung gleichzeitig ausgewertet werden und aktiv aufeinander bezogen werden)?

- **Reihenfolge und Abhängigkeit**: Die Definition von Integrationspunkten und Schnittstellen hängt eng mit der Frage von Reihenfolge und Abhängigkeit zusammen [@schoonenboom2017], ist aber nicht eins-zu-eins dieselbe. In jedem Fall ist vorab zu klären: Gibt es logische und/oder organisatorische Gründe, die erforderlich machen, die qualitative Komponente vor der quantitativen umzusetzen -- oder umgekehrt?

- **Emergenz des Designs**: Ein Kriterium, das bei manchen Autor*innen eine Schlüsselrolle spielt, bei anderen dagegen kaum beachtet wird, betrifft die Frage, wann im Forschungsprozess Designentscheidungen getroffen werden. *Emergenten Designs* stehen vorab *geplante Designs* gegenüber. Dieses Kriterium verdient in meinen Augen in der Praxis durchaus, berücksichtigt zu werden. Schließlich erfordert ein emergentes Design, dass entsprechende Vorkehrungen getroffen werden. Pläne müssen flexibel gehalten werden, und um laufend Anpassungen vornehmen zu können, müssen Zeiten und Räume für Reflexion und Diskussion freigehalten werden. Emergente Designs werden häufig, aber nicht notwendigerweise, eher qualitativ ausgerichtet sein und vom Grunddesign her eher der Logik von Fallstudien folgen. Aber Teil der Idee von Emergenz ist, dass sich eine solche vorab getroffenen Einschätzungen nach und nach als irreführend herausstellen können. 

Neben diesen fast zwingenden Kriterien gibt es eine Reihe von anderen Hinsichten, nach denen Mixed-Methods-Projekte typisiert werden können. So kann zum Beispiel nach den wissenschaftstheoretischen Grundlagen, nach der normativen Orientierung oder nach der (inter-)disziplinären Ausrichtung gefragt werden.



## Wie man Mixed-Methods-Typologien sinnvoll nutzt

Die Typologien, die man in der Literatur findet, sind in der täglichen Praxis schon alleine deswegen schwierig handzuhaben, weil die meisten realen Projekte eher Misch- oder Zwischenformen sind. Das ist eigentlich nur logisch, ergibt sich doch schon bei wenigen Kriterien eine sehr hohe Zahl an theoretisch denkbaren Merkmalskombinationen (sprich: theoretisch denkbaren Typen). Die in manchen Typologien vorgesehene Restkategorie (bei Creswell & Plano Clark wäre das wohl das "Multiphase Design") wird so schnell zur praktisch am häufigsten vorkommenden Variante, was kaum der Grundidee einer nützlichen Typologie entspricht. 

Mixed-Methods-Typologien dürfen daher auf keinen Fall als vollständige und durch und durch systematische Taxonomien missverstanden werden. Sie sind immer Kompromisse, in die verschiedene Erwägungen einfließen (Systematik, Handhabung, Wissenschaftsverständnis ...). Als solche können sie hilfreich sein, weil sie Orientierung bieten und das eigene Projekt leichter darstellbar machen. Sie können aber auch kontraproduktiv sein, wenn sie zu rigide gedeutet werden und dann unflexibel und technokratisch genutzt werden. Auch Typologien sind letztlich nur Reflexionsinstrumente. 

**Die Kernanregung lautet daher**: Unabhängig von der persönlich präferierten Typologie (die Auswahl ist, wie gesagt, groß) sollte zuerst und vor allem der jeweilige Kriterienkatalog durchgearbeitet werden, um das eigene Anliegen besser zu verstehen. Auf dieser Basis kann dann ein dem Projekt entsprechender "Typ" festgelegt werden. Diese Festlegung hilft, weil sie erlaubt, nach vergleichbaren Projekten Ausschau zu halten und die Erfahrungen anderer Forschenden für die Gestaltung des eigenen Projekts zu nutzen. 



