--- 
title: "Mixed Methods"
author: "Ken Horvath"
date: ""
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: " Skriptum zum Seminar an der Uni Zürich im FS2020"
---

#  Multimethodisch forschen -- Skriptum {-}

"Mixed Methods" haben sich in den letzten Jahren als eigenständiges Feld in der sozialwissenschaftlichen Methodenlandschaft etabliert. Hinter dem verlockend schlichten Label verbirgt sich ein heterogenes und dynamisches Gefüge an methodologischen Perspektiven und Positionen, das für die aktuelle Forschungslandschaft in vielen Hinsichten bedeutsam ist. 

Vor diesem Hintergrund führen die folgenden Seiten in die zentrale Aspekte der Mixed-Methods-Forschung ein. Sie sind als digitale Seminarbegleitung gedacht und wollen (1) einen knappen, aber  umfassenden Einblick in Logiken und Techniken multimethodischer Forschung geben und (2) auf einige Punkte aufmerksam machen, die für ein richtiges Verständnis der Thematik grundlegend sind, häufig aber nur unter der Oberfläche abgehandelt werden. 

